### ISSUE TITLE
Notifications to forum subscriptions not working

### ISSUE THREAD

**Issue by infomobi** [mittwald/typo3_forum#184] opened 2016-11-12 10:15 UTC
Is it possible, that notifications to **forum subscriptions** are not yet implemented?
If I subscribe to a forum, I can see the database entry in table tx_typo3forum_domain_model_user_forumsubscription.
But there are no notifications sent on new topics or posts.

Subscriptions on specific topics do work.

Looking into the code, I didn´t find it implemented in NotificationService.php:

`foreach ($topic->getSubscribers() as $subscriber) {
   ...
}`

just notifies subscribers to topics, not whole forums.
Did I miss something?

**Comment by mojobsb** [comment] 2017-04-04 07:58
I need this feature too, but haven't tested yet.
Are there any news about this topic? Can users subscribe to a whole forum?

**Comment by Piperback** [comment] 2017-05-07 09:36
I tested it today with typo3 7.6.14 and typo3_forum 1.0.4.
Subscription of a topic is working like a charm. 
Subscription of a forum doesn't work at all. You don't get any notification for neither new posts nor new topics.

**infomobi** wrote for 6 months that it looks like beeing not implemented at all. I also looked inside code and I have the same opinion. Also for a new topic, there is nohing done after creation: 
`
public function onTopicCreated($topic) {
		if ($topic instanceof Topic) {

		}
	}
`
It would be nice if a developer could give a small feedback on that.

**Comment by Piperback** [comment] 2017-05-07 19:10
I spent some time on fixing it. I changed two files and both are inside the following folder: /typo3conf/ext/typo3_forum/Classes/Service/Notification

Here is my recommendation:

1)NotificationService.php
After the following foreach loop:

```
foreach ($topic->getSubscribers() as $subscriber) {
	if ($subscriber->getUid() != $post->getAuthor()->getUid() ) {
		$marker = [
			'###RECIPIENT###' => $subscriber->getUsername(),
			'###POST_AUTHOR###' => $postAuthor,
			'###TOPIC_LINK###' => $topicLink,
			'###UNSUBSCRIBE_LINK###' => $unSubscribeLink,
			'###FORUM_NAME###' => $this->settings['mailing']['sender']['name']
		];
		$message = $messageTemplate;
		foreach ($marker As $name => $value) {
			$message = str_replace($name, $value, $message);
		}
		$this->htmlMailingService->sendMail($subscriber, $subject, nl2br($message));
	}
}

```
please insert the following lines:

```
$forum = $topic->getForum();
while ($forum)
{
	foreach ($forum->getSubscribers() as $subscriber) {
		if ($subscriber->getUid() != $post->getAuthor()->getUid() ) {
			$marker = [
				'###RECIPIENT###' => $subscriber->getUsername(),
				'###POST_AUTHOR###' => $postAuthor,
				'###TOPIC_LINK###' => $topicLink,
				'###UNSUBSCRIBE_LINK###' => $unSubscribeLink,
				'###FORUM_NAME###' => $this->settings['mailing']['sender']['name']
			];
			$message = $messageTemplate;
			foreach ($marker As $name => $value) {
				$message = str_replace($name, $value, $message);
			}
			$this->htmlMailingService->sendMail($subscriber, $subject, nl2br($message));
		}
	}
	$forum = $forum->getParent();
}
```
This heals that the forum subscriptions are notified for new posts on existing topics. Users that subscribed the parent forum and above (parent's parent ...) should also be notified.

By the way:
For sure refactoring the marker and message stuff to an own function would be better, but more difficult to describe. So sorry for the spaghetti code to advanced users ...

2) SubscriptionListener.php
In my former post I wrote that there is no notification for a new topic. You need to change the following lines:

```
public function onTopicCreated($topic) {
	if ($topic instanceof Topic) {
	}
}

```
to the following lines:

```
public function onTopicCreated($topic) {
	if ($topic instanceof Topic) {
		$this->notificationService->notifySubscribers($topic, $topic->getLastPost());
	}
}

```
If someone has doubts on that, hints are very welcome ...

Cheers
Ralf

**Comment by infomobi** [comment] 2017-05-08 13:42
Tested and seems to work fine.
Danke, Ralf!

**Comment by infomobi** [comment] 2017-05-09 04:54
I found a little problem with your code:
If somone subscribes to a forum and is also subscriber to the parent forum, this person will get two email notifications. if he also subscribed to the topic itself, he gets a third email on every post.
This isn´t that bad, I just wanted to let you know :-)

I´m still happy to have your code.
Thanks again!

**Comment by Piperback** [comment] 2017-06-06 19:44
@infomobi: Thanks for the hint! 

I found another problem with my implementation.
After a new topic is created the link inside notification mail does not include UID. 
The link looks like " .... &tx_typo3forum_pi1[topic]=&cHash .....".
If the user clicks on the link he gets a NULL reference exception.

The problem is that this extension based on extbase does not automatically read back the created UID after adding the new entry.

Here is a link with some background info:
https://forum.typo3.org/index.php/t/154818/ 

To solve this issue you have to add a code line inside
/typo3conf/ext/typo3_forum/Classes/Domain/Factory/Forum/TopicFactory.php
after line 121:
`
$this->topicRepository->add($topic);
//added:
$this->persistenceManager->persistAll();
`
Hope it helps

**Comment by bdsuev** [comment] 2017-08-05 12:05
Thanks a lot for this @Piperback ! It is unfortunate that this extension is still so incomplete after all this time, when the predecessor mm_forum already had all these features.

Would you mind making a pull request so it is included for all users in future versions?

**Comment by bdsuev** [comment] 2017-10-19 14:59
I found another issue: The marker ###FORUM_NAME### is set wrong (l. 118 in NotifactionService.php).

Instead of
`'###FORUM_NAME###' => $this->settings['mailing']['sender']['name']`
it should be 
`'###FORUM_NAME###' => $post->getForum()->getTitle()`

**Comment by AMartinNo1** [comment] 2017-11-13 14:51
Thanks. It has helped a lot. Not sure if I mixed sth. up in the above description. Yet I had the issue that the same template has been used for both, new posts and new topics. So, in addition to above description I was in need of overriding the var `$messageTemplate` as well as the variable `$subject`.

Based on your solutions I have created a more complete script set:
- In my templates I am using `###FORUM_TEAM###` instead of the forum name. So, I have adjusted the code accordingly.
- This script does not send a mail to forum subscribers if a new post has been created within a topic which is not subscribed.
- The scripts are more or less modularized. There surely is more enhancement possible but it's fine for a intermediate step.
- The scripts requires an ext. core hack. Know how to move that to an own ext. without unwanted side effects? Feel free to share your knowledge :)

`\Mittwald\Typo3Forum\Domain\Factory\Forum\TopicFactory::createTopic`
For a quick solution I have made a Core Hack at this point by adding `$this->persistenceManager->persistAll();` after the line where the topic is added to the repository. I tried by overriding the method but there was an issue resolving the topic model. If someone comes up with a solution, it would be nice when you share it.

```ts
config.tx_extbase {
    objects {
        Mittwald\Typo3Forum\Service\Notification\NotificationService.className = Vendor\CustomExt\Service\Notification\NotificationService
        Mittwald\Typo3Forum\Service\Notification\SubscriptionListener.className = Vendor\CustomExt\Service\Notification\SubscriptionListener
    }
}

plugin.tx_typo3forum._LOCAL_LANG.de.Mail_Subscribe_NewTopic_Subject = YOUR TEXT
plugin.tx_typo3forum._LOCAL_LANG.de.Mail_Subscribe_NewTopic_Body = YOUR TEXT
```

```php
namespace Vendor\CustomExt\Service\Notification;

use Mittwald\Typo3Forum\Domain\Model\NotifiableInterface;
use Mittwald\Typo3Forum\Domain\Model\SubscribeableInterface;
use Mittwald\Typo3Forum\Utility\Localization;

class NotificationService extends \Mittwald\Typo3Forum\Service\Notification\NotificationService
{
    public function notifyTopicSubscribers(
        SubscribeableInterface $subscriptionObject,
        NotifiableInterface $notificationObject
    ) {
        $topic = $subscriptionObject;
        $post = $notificationObject;

        $subject = Localization::translate('Mail_Subscribe_NewPost_Subject');
        $messageTemplate = Localization::translate('Mail_Subscribe_NewPost_Body');
        $postAuthor = $post->getAuthor()->getUsername();
        $forum = $topic->getForum();
        $topicLink = $this->getTopicLink($topic->getForum(), $topic, $post);
        $unSubscribeLink = $this->getTopicUnSubscriptionLink($topic, $forum);

        foreach ($topic->getSubscribers() as $subscriber) {
            if ($subscriber->getUid() != $post->getAuthor()->getUid()) {
                $marker = [
                    '###RECIPIENT###' => $subscriber->getUsername(),
                    '###POST_AUTHOR###' => $postAuthor,
                    '###TOPIC_LINK###' => $topicLink,
                    '###UNSUBSCRIBE_LINK###' => $unSubscribeLink,
                    '###FORUM_TEAM###' => $this->settings['mailing']['sender']['name']
                ];
                $message = $messageTemplate;
                foreach ($marker As $name => $value) {
                    $message = str_replace($name, $value, $message);
                }
                $this->htmlMailingService->sendMail($subscriber, $subject, nl2br($message));
            }
        }
    }

    public function notifyForumSubscribers(
        SubscribeableInterface $subscriptionObject,
        NotifiableInterface $notificationObject
    ) {
        $topic = $subscriptionObject;
        $post = $notificationObject;
        $subject = Localization::translate('Mail_Subscribe_NewTopic_Subject');
        $messageTemplate = Localization::translate('Mail_Subscribe_NewTopic_Body');
        $forum = $topic->getForum();
        $topicLink = $this->getTopicLink($forum, $topic, $post);
        $unSubscribeLink = $this->getForumUnSubscriptionLink($topic);

        while ($forum) {
            foreach ($forum->getSubscribers() as $subscriber) {
                if ($topic->getForum()->checkReadAccess($subscriber) && $subscriber->getUid() != $post->getAuthor()->getUid()) {

                    $marker = [
                        '###RECIPIENT###' => $subscriber->getUsername(),
                        '###POST_AUTHOR###' => $post->getAuthor()->getUsername(),
                        '###FORUM_LINK###' => $topicLink,
                        '###UNSUBSCRIBE_LINK###' => $unSubscribeLink,
                        '###FORUM_TEAM###' => $this->settings['mailing']['sender']['name'],
                    ];
                    $message = $messageTemplate;
                    foreach ($marker As $name => $value) {
                        $message = str_replace($name, $value, $message);
                    }
                    $this->htmlMailingService->sendMail($subscriber, $subject, nl2br($message));

                }
            }
            $forum = $forum->getParent();
        }
    }

    protected function getTopicLink($forum, $topic, $post) {
        $arguments = [
            'tx_typo3forum_pi1[controller]' => 'Topic',
            'tx_typo3forum_pi1[action]' => 'show',
            'tx_typo3forum_pi1[topic]' => $topic->getUid(),
            'tx_typo3forum_pi1[forum]' => $forum,
        ];

        $pageNumber = $post->getTopic()->getPageCount();
        if ($pageNumber > 1) {
            $arguments['@widget_0']['currentPage'] = $pageNumber;
        }

        $topicLink = $this->uriBuilder
            ->setTargetPageUid($this->settings['pids']['Forum'])
            ->setArguments($arguments)
            ->setCreateAbsoluteUri(true)
            ->build();
        $this->uriBuilder->reset();

        return '<a href="' . $topicLink . '" title="' . $forum->getTitle() . '">"' . $forum->getTitle() . '"</a>';
    }

    protected function getForumUnSubscriptionLink($topic) {
        $unSubscribeLink = $this->uriBuilder
            ->setTargetPageUid($this->settings['pids']['Forum'])
            ->setArguments([
                'tx_typo3forum_pi1[forum]' => $topic->getForum(),
                'tx_typo3forum_pi1[controller]' => 'User',
                'tx_typo3forum_pi1[action]' => 'subscribe',
                'tx_typo3forum_pi1[unsubscribe]' => 1,
            ])
            ->setCreateAbsoluteUri(true)
            ->build();
        $this->uriBuilder->reset();

        return '<a href="' . $unSubscribeLink . '" title="Nicht mehr abonnieren">nicht mehr abonnieren</a>';
    }

    protected function getTopicUnSubscriptionLink($topic, $forum) {
        $unSubscribeLink = $this->uriBuilder
            ->setTargetPageUid($this->settings['pids']['Forum'])
            ->setArguments([
                'tx_typo3forum_pi1[topic]' => $topic->getUid(),
                'tx_typo3forum_pi1[forum]' => $forum,
                'tx_typo3forum_pi1[controller]' => 'User',
                'tx_typo3forum_pi1[action]' => 'subscribe',
                'tx_typo3forum_pi1[unsubscribe]' => 1,
            ])
            ->setCreateAbsoluteUri(true)
            ->build();
        $this->uriBuilder->reset();

        return '<a href="' . $unSubscribeLink . '" title="Nicht mehr abonnieren">nicht mehr abonnieren</a>';
    }
}
```

```php
namespace Vendor\CustomExt\Service\Notification;

use Mittwald\Typo3Forum\Domain\Model\Forum\Post;
use Mittwald\Typo3Forum\Domain\Model\Forum\Topic;

final class SubscriptionListener
{
    protected $notificationService = NULL;

    public function onPostCreated($post) {
        if ($post instanceof Post) {
            $this->notificationService->notifyTopicSubscribers($post->getTopic(), $post);
        }
    }

    public function onTopicCreated($topic) {
        if ($topic instanceof Topic) {
            $this->notificationService->notifyForumSubscribers($topic, $topic->getLastPost());
        }
    }
}
```

**Closed** 2019-07-19 07:56 UTC
Labels: enhancement
