### ISSUE TITLE
Problem downloading attachments with IE and Firefox

### ISSUE THREAD

**Issue by Sniks6** [mittwald/typo3_forum#227] opened 2017-08-17 09:22 UTC
Hi everyone,

when downloading attached files with Firefox or Internet Explorer, the browser says always the file type would be "html". But in fact it is e.g. a pdf file.

![forumerror001](https://user-images.githubusercontent.com/12664579/29404946-c69602a2-833c-11e7-8a3d-0a55337f552f.jpg)

If I download the file, it is much smaller than the original one. And of course it cannot be opened.

The thing is if I use Google's Chrome browser it works like it should. The file's size is correct and it can be opened.

Here are some facts about the setup:
TYPO3: version 7.6.20
TYPO3-Forum: version 1.1.0 (previously intstalled version: 1.0.4 upgraded afterwards)
Firefox: version 54.0.1
Internet Explorer: version 11.0
Chrome:  60.0.3112.90

Perhaps you could give me a hint.

Thanks,

Alex

**Comment by Sniks6** [comment] 2017-08-28 06:18
Has anybody similar problems? 
Or is there anybody who could give me a hint where to search? 
What could be the problem?

Thank you very much in advance.

Alex

**Comment by sashbash** [comment] 2017-09-13 16:31
I think the problem is located in:
Classes/Controller/PostController.php

function downloadAttachmentAction

should end with 
readfile($attachment->getAbsoluteFilename());
die();

Otherwise, the resulting file after the download has the HTML source code of the page attached to its end. This will likely cause problems when you try to open such broken binary files.

Fixed it for my project. Hope it helps.

Best regards 
Sascha

**Comment by Sniks6** [comment] 2017-09-14 14:41
Thank you very much for your help! That was exactly the point.

Now it works like a charm!

Mittwald, you should take this change into TYPO3 extension repositor. Otherwise the file download doesn't work!

Thanks @sashbash!

Kind regards,
Alex

**Comment by kpurrmann** [comment] 2018-01-05 11:04
FIxed in #234

**Closed by kpurrmann** 2018-01-05 11:04 UTC
